name: Run PostgreSQL and Spring Boot in GitHub Actions

on: [push, pull_request]

jobs:
  postgres_and_springboot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Start PostgreSQL container
      run: docker run --name postgres -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=mypassword -p 5432:5432 -d postgres

    - name: Run Spring Boot backend container
      run: docker run -d --name my-springboot-app --link postgres:db -e SPRING_PROFILES_ACTIVE=dev -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_PASSWORD=mypassword -p 8080:8080 jeffreyamc/lab_e2e_20241_05_springboot:v3
    
    - name: Check Docker containers
      run: docker ps

    - name: Run test_register.sh
      run: |
        chmod +x test_register.sh
        ./test_register.sh
