name: Run PostgreSQL and Spring Boot in GitHub Actions

on: [push, pull_request]

jobs:
  postgres_and_springboot:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mypassword

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Wait for PostgreSQL to be healthy
      run: |
        until docker ps --filter "health=healthy" | grep postgres; do
          echo "Waiting for postgres to be healthy...";
          sleep 5;
        done

    - name: Run Spring Boot backend container
      run: |
        docker run -d -p 8080:8080 jeffreyamc/lab_e2e_20241_05_springboot

    - name: Test backend connection to PostgreSQL
      run: |
        curl -X GET http://localhost:8080/test/connection
